#!/bin/tcsh
# plot AFTAN maps
./CC_aftan_map ctest/COR_TA.M14A_TA.M17A.SAC "Basic AFTAN." \
 "Phase Match Filtering AFTAN."
./CC_aftan_map ftest/COR_TA.M14A_TA.M17A.SAC "Basic AFTAN." \
 "Phase Match Filtering AFTAN."
exit
